<?xml version="1.0" encoding="UTF-8" ?>
<Package name="WordTools" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="translator" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="wikisearch" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="dictionary" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="__init__" src="libs/PyDictionary/__init__.py" />
        <File name="__init__" src="libs/PyDictionary/__init__.pyc" />
        <File name="core" src="libs/PyDictionary/core.py" />
        <File name="core" src="libs/PyDictionary/core.pyc" />
        <File name="script" src="libs/PyDictionary/script.py" />
        <File name="script" src="libs/PyDictionary/script.pyc" />
        <File name="test_pydictionary" src="libs/PyDictionary/test_pydictionary.py" />
        <File name="test_pydictionary" src="libs/PyDictionary/test_pydictionary.pyc" />
        <File name="utils" src="libs/PyDictionary/utils.py" />
        <File name="utils" src="libs/PyDictionary/utils.pyc" />
        <File name="__init__" src="libs/bs4/__init__.py" />
        <File name="__init__" src="libs/bs4/__init__.pyc" />
        <File name="__init__" src="libs/bs4/builder/__init__.py" />
        <File name="__init__" src="libs/bs4/builder/__init__.pyc" />
        <File name="_html5lib" src="libs/bs4/builder/_html5lib.py" />
        <File name="_html5lib" src="libs/bs4/builder/_html5lib.pyc" />
        <File name="_htmlparser" src="libs/bs4/builder/_htmlparser.py" />
        <File name="_htmlparser" src="libs/bs4/builder/_htmlparser.pyc" />
        <File name="_lxml" src="libs/bs4/builder/_lxml.py" />
        <File name="_lxml" src="libs/bs4/builder/_lxml.pyc" />
        <File name="dammit" src="libs/bs4/dammit.py" />
        <File name="dammit" src="libs/bs4/dammit.pyc" />
        <File name="diagnose" src="libs/bs4/diagnose.py" />
        <File name="diagnose" src="libs/bs4/diagnose.pyc" />
        <File name="element" src="libs/bs4/element.py" />
        <File name="element" src="libs/bs4/element.pyc" />
        <File name="formatter" src="libs/bs4/formatter.py" />
        <File name="formatter" src="libs/bs4/formatter.pyc" />
        <File name="testing" src="libs/bs4/testing.py" />
        <File name="testing" src="libs/bs4/testing.pyc" />
        <File name="__init__" src="libs/bs4/tests/__init__.py" />
        <File name="__init__" src="libs/bs4/tests/__init__.pyc" />
        <File name="test_builder_registry" src="libs/bs4/tests/test_builder_registry.py" />
        <File name="test_builder_registry" src="libs/bs4/tests/test_builder_registry.pyc" />
        <File name="test_docs" src="libs/bs4/tests/test_docs.py" />
        <File name="test_docs" src="libs/bs4/tests/test_docs.pyc" />
        <File name="test_html5lib" src="libs/bs4/tests/test_html5lib.py" />
        <File name="test_html5lib" src="libs/bs4/tests/test_html5lib.pyc" />
        <File name="test_htmlparser" src="libs/bs4/tests/test_htmlparser.py" />
        <File name="test_htmlparser" src="libs/bs4/tests/test_htmlparser.pyc" />
        <File name="test_lxml" src="libs/bs4/tests/test_lxml.py" />
        <File name="test_lxml" src="libs/bs4/tests/test_lxml.pyc" />
        <File name="test_soup" src="libs/bs4/tests/test_soup.py" />
        <File name="test_soup" src="libs/bs4/tests/test_soup.pyc" />
        <File name="test_tree" src="libs/bs4/tests/test_tree.py" />
        <File name="test_tree" src="libs/bs4/tests/test_tree.pyc" />
        <File name="goslate" src="libs/goslate.py" />
        <File name="__init__" src="libs/mtranslate/__init__.py" />
        <File name="__init__" src="libs/mtranslate/__init__.pyc" />
        <File name="__main__" src="libs/mtranslate/__main__.py" />
        <File name="__main__" src="libs/mtranslate/__main__.pyc" />
        <File name="core" src="libs/mtranslate/core.py" />
        <File name="core" src="libs/mtranslate/core.pyc" />
        <File name="__init__" src="libs/wikipedia/__init__.py" />
        <File name="__init__" src="libs/wikipedia/__init__.pyc" />
        <File name="exceptions" src="libs/wikipedia/exceptions.py" />
        <File name="exceptions" src="libs/wikipedia/exceptions.pyc" />
        <File name="util" src="libs/wikipedia/util.py" />
        <File name="util" src="libs/wikipedia/util.pyc" />
        <File name="wikipedia" src="libs/wikipedia/wikipedia.py" />
        <File name="wikipedia" src="libs/wikipedia/wikipedia.pyc" />
        <File name="__init__" src="libs/unidecode/__init__.py" />
        <File name="__main__" src="libs/unidecode/__main__.py" />
        <File name="py" src="libs/unidecode/py.typed" />
        <File name="util" src="libs/unidecode/util.py" />
        <File name="x000" src="libs/unidecode/x000.py" />
        <File name="x001" src="libs/unidecode/x001.py" />
        <File name="x002" src="libs/unidecode/x002.py" />
        <File name="x003" src="libs/unidecode/x003.py" />
        <File name="x004" src="libs/unidecode/x004.py" />
        <File name="x005" src="libs/unidecode/x005.py" />
        <File name="x006" src="libs/unidecode/x006.py" />
        <File name="x007" src="libs/unidecode/x007.py" />
        <File name="x009" src="libs/unidecode/x009.py" />
        <File name="x00a" src="libs/unidecode/x00a.py" />
        <File name="x00b" src="libs/unidecode/x00b.py" />
        <File name="x00c" src="libs/unidecode/x00c.py" />
        <File name="x00d" src="libs/unidecode/x00d.py" />
        <File name="x00e" src="libs/unidecode/x00e.py" />
        <File name="x00f" src="libs/unidecode/x00f.py" />
        <File name="x010" src="libs/unidecode/x010.py" />
        <File name="x011" src="libs/unidecode/x011.py" />
        <File name="x012" src="libs/unidecode/x012.py" />
        <File name="x013" src="libs/unidecode/x013.py" />
        <File name="x014" src="libs/unidecode/x014.py" />
        <File name="x015" src="libs/unidecode/x015.py" />
        <File name="x016" src="libs/unidecode/x016.py" />
        <File name="x017" src="libs/unidecode/x017.py" />
        <File name="x018" src="libs/unidecode/x018.py" />
        <File name="x01d" src="libs/unidecode/x01d.py" />
        <File name="x01e" src="libs/unidecode/x01e.py" />
        <File name="x01f" src="libs/unidecode/x01f.py" />
        <File name="x020" src="libs/unidecode/x020.py" />
        <File name="x021" src="libs/unidecode/x021.py" />
        <File name="x022" src="libs/unidecode/x022.py" />
        <File name="x023" src="libs/unidecode/x023.py" />
        <File name="x024" src="libs/unidecode/x024.py" />
        <File name="x025" src="libs/unidecode/x025.py" />
        <File name="x026" src="libs/unidecode/x026.py" />
        <File name="x027" src="libs/unidecode/x027.py" />
        <File name="x028" src="libs/unidecode/x028.py" />
        <File name="x029" src="libs/unidecode/x029.py" />
        <File name="x02a" src="libs/unidecode/x02a.py" />
        <File name="x02c" src="libs/unidecode/x02c.py" />
        <File name="x02e" src="libs/unidecode/x02e.py" />
        <File name="x02f" src="libs/unidecode/x02f.py" />
        <File name="x030" src="libs/unidecode/x030.py" />
        <File name="x031" src="libs/unidecode/x031.py" />
        <File name="x032" src="libs/unidecode/x032.py" />
        <File name="x033" src="libs/unidecode/x033.py" />
        <File name="x04d" src="libs/unidecode/x04d.py" />
        <File name="x04e" src="libs/unidecode/x04e.py" />
        <File name="x04f" src="libs/unidecode/x04f.py" />
        <File name="x050" src="libs/unidecode/x050.py" />
        <File name="x051" src="libs/unidecode/x051.py" />
        <File name="x052" src="libs/unidecode/x052.py" />
        <File name="x053" src="libs/unidecode/x053.py" />
        <File name="x054" src="libs/unidecode/x054.py" />
        <File name="x055" src="libs/unidecode/x055.py" />
        <File name="x056" src="libs/unidecode/x056.py" />
        <File name="x057" src="libs/unidecode/x057.py" />
        <File name="x058" src="libs/unidecode/x058.py" />
        <File name="x059" src="libs/unidecode/x059.py" />
        <File name="x05a" src="libs/unidecode/x05a.py" />
        <File name="x05b" src="libs/unidecode/x05b.py" />
        <File name="x05c" src="libs/unidecode/x05c.py" />
        <File name="x05d" src="libs/unidecode/x05d.py" />
        <File name="x05e" src="libs/unidecode/x05e.py" />
        <File name="x05f" src="libs/unidecode/x05f.py" />
        <File name="x060" src="libs/unidecode/x060.py" />
        <File name="x061" src="libs/unidecode/x061.py" />
        <File name="x062" src="libs/unidecode/x062.py" />
        <File name="x063" src="libs/unidecode/x063.py" />
        <File name="x064" src="libs/unidecode/x064.py" />
        <File name="x065" src="libs/unidecode/x065.py" />
        <File name="x066" src="libs/unidecode/x066.py" />
        <File name="x067" src="libs/unidecode/x067.py" />
        <File name="x068" src="libs/unidecode/x068.py" />
        <File name="x069" src="libs/unidecode/x069.py" />
        <File name="x06a" src="libs/unidecode/x06a.py" />
        <File name="x06b" src="libs/unidecode/x06b.py" />
        <File name="x06c" src="libs/unidecode/x06c.py" />
        <File name="x06d" src="libs/unidecode/x06d.py" />
        <File name="x06e" src="libs/unidecode/x06e.py" />
        <File name="x06f" src="libs/unidecode/x06f.py" />
        <File name="x070" src="libs/unidecode/x070.py" />
        <File name="x071" src="libs/unidecode/x071.py" />
        <File name="x072" src="libs/unidecode/x072.py" />
        <File name="x073" src="libs/unidecode/x073.py" />
        <File name="x074" src="libs/unidecode/x074.py" />
        <File name="x075" src="libs/unidecode/x075.py" />
        <File name="x076" src="libs/unidecode/x076.py" />
        <File name="x077" src="libs/unidecode/x077.py" />
        <File name="x078" src="libs/unidecode/x078.py" />
        <File name="x079" src="libs/unidecode/x079.py" />
        <File name="x07a" src="libs/unidecode/x07a.py" />
        <File name="x07b" src="libs/unidecode/x07b.py" />
        <File name="x07c" src="libs/unidecode/x07c.py" />
        <File name="x07d" src="libs/unidecode/x07d.py" />
        <File name="x07e" src="libs/unidecode/x07e.py" />
        <File name="x07f" src="libs/unidecode/x07f.py" />
        <File name="x080" src="libs/unidecode/x080.py" />
        <File name="x081" src="libs/unidecode/x081.py" />
        <File name="x082" src="libs/unidecode/x082.py" />
        <File name="x083" src="libs/unidecode/x083.py" />
        <File name="x084" src="libs/unidecode/x084.py" />
        <File name="x085" src="libs/unidecode/x085.py" />
        <File name="x086" src="libs/unidecode/x086.py" />
        <File name="x087" src="libs/unidecode/x087.py" />
        <File name="x088" src="libs/unidecode/x088.py" />
        <File name="x089" src="libs/unidecode/x089.py" />
        <File name="x08a" src="libs/unidecode/x08a.py" />
        <File name="x08b" src="libs/unidecode/x08b.py" />
        <File name="x08c" src="libs/unidecode/x08c.py" />
        <File name="x08d" src="libs/unidecode/x08d.py" />
        <File name="x08e" src="libs/unidecode/x08e.py" />
        <File name="x08f" src="libs/unidecode/x08f.py" />
        <File name="x090" src="libs/unidecode/x090.py" />
        <File name="x091" src="libs/unidecode/x091.py" />
        <File name="x092" src="libs/unidecode/x092.py" />
        <File name="x093" src="libs/unidecode/x093.py" />
        <File name="x094" src="libs/unidecode/x094.py" />
        <File name="x095" src="libs/unidecode/x095.py" />
        <File name="x096" src="libs/unidecode/x096.py" />
        <File name="x097" src="libs/unidecode/x097.py" />
        <File name="x098" src="libs/unidecode/x098.py" />
        <File name="x099" src="libs/unidecode/x099.py" />
        <File name="x09a" src="libs/unidecode/x09a.py" />
        <File name="x09b" src="libs/unidecode/x09b.py" />
        <File name="x09c" src="libs/unidecode/x09c.py" />
        <File name="x09d" src="libs/unidecode/x09d.py" />
        <File name="x09e" src="libs/unidecode/x09e.py" />
        <File name="x09f" src="libs/unidecode/x09f.py" />
        <File name="x0a0" src="libs/unidecode/x0a0.py" />
        <File name="x0a1" src="libs/unidecode/x0a1.py" />
        <File name="x0a2" src="libs/unidecode/x0a2.py" />
        <File name="x0a3" src="libs/unidecode/x0a3.py" />
        <File name="x0a4" src="libs/unidecode/x0a4.py" />
        <File name="x0ac" src="libs/unidecode/x0ac.py" />
        <File name="x0ad" src="libs/unidecode/x0ad.py" />
        <File name="x0ae" src="libs/unidecode/x0ae.py" />
        <File name="x0af" src="libs/unidecode/x0af.py" />
        <File name="x0b0" src="libs/unidecode/x0b0.py" />
        <File name="x0b1" src="libs/unidecode/x0b1.py" />
        <File name="x0b2" src="libs/unidecode/x0b2.py" />
        <File name="x0b3" src="libs/unidecode/x0b3.py" />
        <File name="x0b4" src="libs/unidecode/x0b4.py" />
        <File name="x0b5" src="libs/unidecode/x0b5.py" />
        <File name="x0b6" src="libs/unidecode/x0b6.py" />
        <File name="x0b7" src="libs/unidecode/x0b7.py" />
        <File name="x0b8" src="libs/unidecode/x0b8.py" />
        <File name="x0b9" src="libs/unidecode/x0b9.py" />
        <File name="x0ba" src="libs/unidecode/x0ba.py" />
        <File name="x0bb" src="libs/unidecode/x0bb.py" />
        <File name="x0bc" src="libs/unidecode/x0bc.py" />
        <File name="x0bd" src="libs/unidecode/x0bd.py" />
        <File name="x0be" src="libs/unidecode/x0be.py" />
        <File name="x0bf" src="libs/unidecode/x0bf.py" />
        <File name="x0c0" src="libs/unidecode/x0c0.py" />
        <File name="x0c1" src="libs/unidecode/x0c1.py" />
        <File name="x0c2" src="libs/unidecode/x0c2.py" />
        <File name="x0c3" src="libs/unidecode/x0c3.py" />
        <File name="x0c4" src="libs/unidecode/x0c4.py" />
        <File name="x0c5" src="libs/unidecode/x0c5.py" />
        <File name="x0c6" src="libs/unidecode/x0c6.py" />
        <File name="x0c7" src="libs/unidecode/x0c7.py" />
        <File name="x0c8" src="libs/unidecode/x0c8.py" />
        <File name="x0c9" src="libs/unidecode/x0c9.py" />
        <File name="x0ca" src="libs/unidecode/x0ca.py" />
        <File name="x0cb" src="libs/unidecode/x0cb.py" />
        <File name="x0cc" src="libs/unidecode/x0cc.py" />
        <File name="x0cd" src="libs/unidecode/x0cd.py" />
        <File name="x0ce" src="libs/unidecode/x0ce.py" />
        <File name="x0cf" src="libs/unidecode/x0cf.py" />
        <File name="x0d0" src="libs/unidecode/x0d0.py" />
        <File name="x0d1" src="libs/unidecode/x0d1.py" />
        <File name="x0d2" src="libs/unidecode/x0d2.py" />
        <File name="x0d3" src="libs/unidecode/x0d3.py" />
        <File name="x0d4" src="libs/unidecode/x0d4.py" />
        <File name="x0d5" src="libs/unidecode/x0d5.py" />
        <File name="x0d6" src="libs/unidecode/x0d6.py" />
        <File name="x0d7" src="libs/unidecode/x0d7.py" />
        <File name="x0f9" src="libs/unidecode/x0f9.py" />
        <File name="x0fa" src="libs/unidecode/x0fa.py" />
        <File name="x0fb" src="libs/unidecode/x0fb.py" />
        <File name="x0fc" src="libs/unidecode/x0fc.py" />
        <File name="x0fd" src="libs/unidecode/x0fd.py" />
        <File name="x0fe" src="libs/unidecode/x0fe.py" />
        <File name="x0ff" src="libs/unidecode/x0ff.py" />
        <File name="x1d4" src="libs/unidecode/x1d4.py" />
        <File name="x1d5" src="libs/unidecode/x1d5.py" />
        <File name="x1d6" src="libs/unidecode/x1d6.py" />
        <File name="x1d7" src="libs/unidecode/x1d7.py" />
        <File name="x1f1" src="libs/unidecode/x1f1.py" />
        <File name="x1f6" src="libs/unidecode/x1f6.py" />
        <File name="__init__" src="libs/unidecode/__init__.pyc" />
        <File name="__init__" src="libs/unidecode/__init__.pyi" />
        <File name="__main__" src="libs/unidecode/__main__.pyc" />
        <File name="util" src="libs/unidecode/util.pyc" />
        <File name="x000" src="libs/unidecode/x000.pyc" />
        <File name="x001" src="libs/unidecode/x001.pyc" />
        <File name="x002" src="libs/unidecode/x002.pyc" />
        <File name="x003" src="libs/unidecode/x003.pyc" />
        <File name="x004" src="libs/unidecode/x004.pyc" />
        <File name="x005" src="libs/unidecode/x005.pyc" />
        <File name="x006" src="libs/unidecode/x006.pyc" />
        <File name="x007" src="libs/unidecode/x007.pyc" />
        <File name="x009" src="libs/unidecode/x009.pyc" />
        <File name="x00a" src="libs/unidecode/x00a.pyc" />
        <File name="x00b" src="libs/unidecode/x00b.pyc" />
        <File name="x00c" src="libs/unidecode/x00c.pyc" />
        <File name="x00d" src="libs/unidecode/x00d.pyc" />
        <File name="x00e" src="libs/unidecode/x00e.pyc" />
        <File name="x00f" src="libs/unidecode/x00f.pyc" />
        <File name="x010" src="libs/unidecode/x010.pyc" />
        <File name="x011" src="libs/unidecode/x011.pyc" />
        <File name="x012" src="libs/unidecode/x012.pyc" />
        <File name="x013" src="libs/unidecode/x013.pyc" />
        <File name="x014" src="libs/unidecode/x014.pyc" />
        <File name="x015" src="libs/unidecode/x015.pyc" />
        <File name="x016" src="libs/unidecode/x016.pyc" />
        <File name="x017" src="libs/unidecode/x017.pyc" />
        <File name="x018" src="libs/unidecode/x018.pyc" />
        <File name="x01d" src="libs/unidecode/x01d.pyc" />
        <File name="x01e" src="libs/unidecode/x01e.pyc" />
        <File name="x01f" src="libs/unidecode/x01f.pyc" />
        <File name="x020" src="libs/unidecode/x020.pyc" />
        <File name="x021" src="libs/unidecode/x021.pyc" />
        <File name="x022" src="libs/unidecode/x022.pyc" />
        <File name="x023" src="libs/unidecode/x023.pyc" />
        <File name="x024" src="libs/unidecode/x024.pyc" />
        <File name="x025" src="libs/unidecode/x025.pyc" />
        <File name="x026" src="libs/unidecode/x026.pyc" />
        <File name="x027" src="libs/unidecode/x027.pyc" />
        <File name="x028" src="libs/unidecode/x028.pyc" />
        <File name="x029" src="libs/unidecode/x029.pyc" />
        <File name="x02a" src="libs/unidecode/x02a.pyc" />
        <File name="x02c" src="libs/unidecode/x02c.pyc" />
        <File name="x02e" src="libs/unidecode/x02e.pyc" />
        <File name="x02f" src="libs/unidecode/x02f.pyc" />
        <File name="x030" src="libs/unidecode/x030.pyc" />
        <File name="x031" src="libs/unidecode/x031.pyc" />
        <File name="x032" src="libs/unidecode/x032.pyc" />
        <File name="x033" src="libs/unidecode/x033.pyc" />
        <File name="x04d" src="libs/unidecode/x04d.pyc" />
        <File name="x04e" src="libs/unidecode/x04e.pyc" />
        <File name="x04f" src="libs/unidecode/x04f.pyc" />
        <File name="x050" src="libs/unidecode/x050.pyc" />
        <File name="x051" src="libs/unidecode/x051.pyc" />
        <File name="x052" src="libs/unidecode/x052.pyc" />
        <File name="x053" src="libs/unidecode/x053.pyc" />
        <File name="x054" src="libs/unidecode/x054.pyc" />
        <File name="x055" src="libs/unidecode/x055.pyc" />
        <File name="x056" src="libs/unidecode/x056.pyc" />
        <File name="x057" src="libs/unidecode/x057.pyc" />
        <File name="x058" src="libs/unidecode/x058.pyc" />
        <File name="x059" src="libs/unidecode/x059.pyc" />
        <File name="x05a" src="libs/unidecode/x05a.pyc" />
        <File name="x05b" src="libs/unidecode/x05b.pyc" />
        <File name="x05c" src="libs/unidecode/x05c.pyc" />
        <File name="x05d" src="libs/unidecode/x05d.pyc" />
        <File name="x05e" src="libs/unidecode/x05e.pyc" />
        <File name="x05f" src="libs/unidecode/x05f.pyc" />
        <File name="x060" src="libs/unidecode/x060.pyc" />
        <File name="x061" src="libs/unidecode/x061.pyc" />
        <File name="x062" src="libs/unidecode/x062.pyc" />
        <File name="x063" src="libs/unidecode/x063.pyc" />
        <File name="x064" src="libs/unidecode/x064.pyc" />
        <File name="x065" src="libs/unidecode/x065.pyc" />
        <File name="x066" src="libs/unidecode/x066.pyc" />
        <File name="x067" src="libs/unidecode/x067.pyc" />
        <File name="x068" src="libs/unidecode/x068.pyc" />
        <File name="x069" src="libs/unidecode/x069.pyc" />
        <File name="x06a" src="libs/unidecode/x06a.pyc" />
        <File name="x06b" src="libs/unidecode/x06b.pyc" />
        <File name="x06c" src="libs/unidecode/x06c.pyc" />
        <File name="x06d" src="libs/unidecode/x06d.pyc" />
        <File name="x06e" src="libs/unidecode/x06e.pyc" />
        <File name="x06f" src="libs/unidecode/x06f.pyc" />
        <File name="x070" src="libs/unidecode/x070.pyc" />
        <File name="x071" src="libs/unidecode/x071.pyc" />
        <File name="x072" src="libs/unidecode/x072.pyc" />
        <File name="x073" src="libs/unidecode/x073.pyc" />
        <File name="x074" src="libs/unidecode/x074.pyc" />
        <File name="x075" src="libs/unidecode/x075.pyc" />
        <File name="x076" src="libs/unidecode/x076.pyc" />
        <File name="x077" src="libs/unidecode/x077.pyc" />
        <File name="x078" src="libs/unidecode/x078.pyc" />
        <File name="x079" src="libs/unidecode/x079.pyc" />
        <File name="x07a" src="libs/unidecode/x07a.pyc" />
        <File name="x07b" src="libs/unidecode/x07b.pyc" />
        <File name="x07c" src="libs/unidecode/x07c.pyc" />
        <File name="x07d" src="libs/unidecode/x07d.pyc" />
        <File name="x07e" src="libs/unidecode/x07e.pyc" />
        <File name="x07f" src="libs/unidecode/x07f.pyc" />
        <File name="x080" src="libs/unidecode/x080.pyc" />
        <File name="x081" src="libs/unidecode/x081.pyc" />
        <File name="x082" src="libs/unidecode/x082.pyc" />
        <File name="x083" src="libs/unidecode/x083.pyc" />
        <File name="x084" src="libs/unidecode/x084.pyc" />
        <File name="x085" src="libs/unidecode/x085.pyc" />
        <File name="x086" src="libs/unidecode/x086.pyc" />
        <File name="x087" src="libs/unidecode/x087.pyc" />
        <File name="x088" src="libs/unidecode/x088.pyc" />
        <File name="x089" src="libs/unidecode/x089.pyc" />
        <File name="x08a" src="libs/unidecode/x08a.pyc" />
        <File name="x08b" src="libs/unidecode/x08b.pyc" />
        <File name="x08c" src="libs/unidecode/x08c.pyc" />
        <File name="x08d" src="libs/unidecode/x08d.pyc" />
        <File name="x08e" src="libs/unidecode/x08e.pyc" />
        <File name="x08f" src="libs/unidecode/x08f.pyc" />
        <File name="x090" src="libs/unidecode/x090.pyc" />
        <File name="x091" src="libs/unidecode/x091.pyc" />
        <File name="x092" src="libs/unidecode/x092.pyc" />
        <File name="x093" src="libs/unidecode/x093.pyc" />
        <File name="x094" src="libs/unidecode/x094.pyc" />
        <File name="x095" src="libs/unidecode/x095.pyc" />
        <File name="x096" src="libs/unidecode/x096.pyc" />
        <File name="x097" src="libs/unidecode/x097.pyc" />
        <File name="x098" src="libs/unidecode/x098.pyc" />
        <File name="x099" src="libs/unidecode/x099.pyc" />
        <File name="x09a" src="libs/unidecode/x09a.pyc" />
        <File name="x09b" src="libs/unidecode/x09b.pyc" />
        <File name="x09c" src="libs/unidecode/x09c.pyc" />
        <File name="x09d" src="libs/unidecode/x09d.pyc" />
        <File name="x09e" src="libs/unidecode/x09e.pyc" />
        <File name="x09f" src="libs/unidecode/x09f.pyc" />
        <File name="x0a0" src="libs/unidecode/x0a0.pyc" />
        <File name="x0a1" src="libs/unidecode/x0a1.pyc" />
        <File name="x0a2" src="libs/unidecode/x0a2.pyc" />
        <File name="x0a3" src="libs/unidecode/x0a3.pyc" />
        <File name="x0a4" src="libs/unidecode/x0a4.pyc" />
        <File name="x0ac" src="libs/unidecode/x0ac.pyc" />
        <File name="x0ad" src="libs/unidecode/x0ad.pyc" />
        <File name="x0ae" src="libs/unidecode/x0ae.pyc" />
        <File name="x0af" src="libs/unidecode/x0af.pyc" />
        <File name="x0b0" src="libs/unidecode/x0b0.pyc" />
        <File name="x0b1" src="libs/unidecode/x0b1.pyc" />
        <File name="x0b2" src="libs/unidecode/x0b2.pyc" />
        <File name="x0b3" src="libs/unidecode/x0b3.pyc" />
        <File name="x0b4" src="libs/unidecode/x0b4.pyc" />
        <File name="x0b5" src="libs/unidecode/x0b5.pyc" />
        <File name="x0b6" src="libs/unidecode/x0b6.pyc" />
        <File name="x0b7" src="libs/unidecode/x0b7.pyc" />
        <File name="x0b8" src="libs/unidecode/x0b8.pyc" />
        <File name="x0b9" src="libs/unidecode/x0b9.pyc" />
        <File name="x0ba" src="libs/unidecode/x0ba.pyc" />
        <File name="x0bb" src="libs/unidecode/x0bb.pyc" />
        <File name="x0bc" src="libs/unidecode/x0bc.pyc" />
        <File name="x0bd" src="libs/unidecode/x0bd.pyc" />
        <File name="x0be" src="libs/unidecode/x0be.pyc" />
        <File name="x0bf" src="libs/unidecode/x0bf.pyc" />
        <File name="x0c0" src="libs/unidecode/x0c0.pyc" />
        <File name="x0c1" src="libs/unidecode/x0c1.pyc" />
        <File name="x0c2" src="libs/unidecode/x0c2.pyc" />
        <File name="x0c3" src="libs/unidecode/x0c3.pyc" />
        <File name="x0c4" src="libs/unidecode/x0c4.pyc" />
        <File name="x0c5" src="libs/unidecode/x0c5.pyc" />
        <File name="x0c6" src="libs/unidecode/x0c6.pyc" />
        <File name="x0c7" src="libs/unidecode/x0c7.pyc" />
        <File name="x0c8" src="libs/unidecode/x0c8.pyc" />
        <File name="x0c9" src="libs/unidecode/x0c9.pyc" />
        <File name="x0ca" src="libs/unidecode/x0ca.pyc" />
        <File name="x0cb" src="libs/unidecode/x0cb.pyc" />
        <File name="x0cc" src="libs/unidecode/x0cc.pyc" />
        <File name="x0cd" src="libs/unidecode/x0cd.pyc" />
        <File name="x0ce" src="libs/unidecode/x0ce.pyc" />
        <File name="x0cf" src="libs/unidecode/x0cf.pyc" />
        <File name="x0d0" src="libs/unidecode/x0d0.pyc" />
        <File name="x0d1" src="libs/unidecode/x0d1.pyc" />
        <File name="x0d2" src="libs/unidecode/x0d2.pyc" />
        <File name="x0d3" src="libs/unidecode/x0d3.pyc" />
        <File name="x0d4" src="libs/unidecode/x0d4.pyc" />
        <File name="x0d5" src="libs/unidecode/x0d5.pyc" />
        <File name="x0d6" src="libs/unidecode/x0d6.pyc" />
        <File name="x0d7" src="libs/unidecode/x0d7.pyc" />
        <File name="x0f9" src="libs/unidecode/x0f9.pyc" />
        <File name="x0fa" src="libs/unidecode/x0fa.pyc" />
        <File name="x0fb" src="libs/unidecode/x0fb.pyc" />
        <File name="x0fc" src="libs/unidecode/x0fc.pyc" />
        <File name="x0fd" src="libs/unidecode/x0fd.pyc" />
        <File name="x0fe" src="libs/unidecode/x0fe.pyc" />
        <File name="x0ff" src="libs/unidecode/x0ff.pyc" />
        <File name="x1d4" src="libs/unidecode/x1d4.pyc" />
        <File name="x1d5" src="libs/unidecode/x1d5.pyc" />
        <File name="x1d6" src="libs/unidecode/x1d6.pyc" />
        <File name="x1d7" src="libs/unidecode/x1d7.pyc" />
        <File name="x1f1" src="libs/unidecode/x1f1.pyc" />
        <File name="x1f6" src="libs/unidecode/x1f6.pyc" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
    </Translations>
</Package>
