<?xml version="1.0" encoding="UTF-8" ?>
<Package name="CAIR Client" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="cair_client" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="DialogueMode" src="html/img/DialogueMode.png" />
        <File name="ExecutionMode" src="html/img/ExecutionMode.png" />
        <File name="PrivacyMode" src="html/img/PrivacyMode.png" />
        <File name="gzip" src="libs/gzip.py" />
        <File name="nuance_vectors" src="nuance_vectors.json" />
        <File name="RICE" src="html/img/RICE.png" />
        <File name="CAIRclient_SoftBank_actions" src="libs/cair_libraries/client_softbank_action_manager.py" />
        <File name="CAIRclient_SoftBank_utils" src="libs/cair_libraries/client_softbank_utils.py" />
        <File name="CAIRclient_alterego_utils" src="libs/cair_libraries/client_alterego_utils.py" />
        <File name="CAIRclient_utils" src="libs/cair_libraries/client_utils.py" />
        <File name="DialogueNuances" src="libs/cair_libraries/dialogue_nuances.py" />
        <File name="DialogueSentencePiece" src="libs/cair_libraries/dialogue_sentence_piece.py" />
        <File name="DialogueState" src="libs/cair_libraries/dialogue_state.py" />
        <File name="DialogueStatistics" src="libs/cair_libraries/dialogue_statistics.py" />
        <File name="DialogueTurn" src="libs/cair_libraries/dialogue_turn.py" />
        <File name="SpeakerInfo" src="libs/cair_libraries/speaker_info.py" />
        <File name="Utils" src="libs/cair_libraries/server_utils.py" />
        <File name="__init__" src="libs/cair_libraries/__init__.py" />
        <File name="trigger_sentences_cn-CN" src="trigger_sentences/trigger_sentences_cn-CN.txt" />
        <File name="trigger_sentences_en-US" src="trigger_sentences/trigger_sentences_en-US.txt" />
        <File name="trigger_sentences_es-ES" src="trigger_sentences/trigger_sentences_es-ES.txt" />
        <File name="trigger_sentences_fr-FR" src="trigger_sentences/trigger_sentences_fr-FR.txt" />
        <File name="trigger_sentences_it-IT" src="trigger_sentences/trigger_sentences_it-IT.txt" />
        <File name="QR_code" src="html/img/QR_code.png" />
        <File name="client_softbank_personalization_server" src="libs/cair_libraries/client_softbank_personalization_server.py" />
        <File name="client_personalization_server" src="libs/cair_libraries/client_personalization_server.py" />
        <File name="REQUESTED" src="libs/Flask-1.1.2.dist-info/REQUESTED" />
        <File name="__init__" src="libs/click/__init__.py" />
        <File name="__init__" src="libs/click/__init__.pyc" />
        <File name="_bashcomplete" src="libs/click/_bashcomplete.py" />
        <File name="_bashcomplete" src="libs/click/_bashcomplete.pyc" />
        <File name="_compat" src="libs/click/_compat.pyc" />
        <File name="_termui_impl" src="libs/click/_termui_impl.py" />
        <File name="_termui_impl" src="libs/click/_termui_impl.pyc" />
        <File name="_textwrap" src="libs/click/_textwrap.py" />
        <File name="_textwrap" src="libs/click/_textwrap.pyc" />
        <File name="_unicodefun" src="libs/click/_unicodefun.py" />
        <File name="_unicodefun" src="libs/click/_unicodefun.pyc" />
        <File name="_winconsole" src="libs/click/_winconsole.py" />
        <File name="_winconsole" src="libs/click/_winconsole.pyc" />
        <File name="decorators" src="libs/click/decorators.py" />
        <File name="decorators" src="libs/click/decorators.pyc" />
        <File name="exceptions" src="libs/click/exceptions.py" />
        <File name="exceptions" src="libs/click/exceptions.pyc" />
        <File name="formatting" src="libs/click/formatting.py" />
        <File name="formatting" src="libs/click/formatting.pyc" />
        <File name="globals" src="libs/click/globals.py" />
        <File name="globals" src="libs/click/globals.pyc" />
        <File name="parser" src="libs/click/parser.py" />
        <File name="parser" src="libs/click/parser.pyc" />
        <File name="termui" src="libs/click/termui.py" />
        <File name="termui" src="libs/click/termui.pyc" />
        <File name="testing" src="libs/click/testing.py" />
        <File name="testing" src="libs/click/testing.pyc" />
        <File name="types" src="libs/click/types.py" />
        <File name="types" src="libs/click/types.pyc" />
        <File name="utils" src="libs/click/utils.py" />
        <File name="utils" src="libs/click/utils.pyc" />
        <File name="__init__" src="libs/jinja2/__init__.pyc" />
        <File name="_compat" src="libs/jinja2/_compat.pyc" />
        <File name="_identifier" src="libs/jinja2/_identifier.pyc" />
        <File name="bccache" src="libs/jinja2/bccache.pyc" />
        <File name="compiler" src="libs/jinja2/compiler.pyc" />
        <File name="constants" src="libs/jinja2/constants.pyc" />
        <File name="debug" src="libs/jinja2/debug.pyc" />
        <File name="defaults" src="libs/jinja2/defaults.pyc" />
        <File name="environment" src="libs/jinja2/environment.pyc" />
        <File name="exceptions" src="libs/jinja2/exceptions.pyc" />
        <File name="ext" src="libs/jinja2/ext.pyc" />
        <File name="filters" src="libs/jinja2/filters.pyc" />
        <File name="idtracking" src="libs/jinja2/idtracking.pyc" />
        <File name="lexer" src="libs/jinja2/lexer.pyc" />
        <File name="loaders" src="libs/jinja2/loaders.pyc" />
        <File name="meta" src="libs/jinja2/meta.pyc" />
        <File name="nativetypes" src="libs/jinja2/nativetypes.pyc" />
        <File name="nodes" src="libs/jinja2/nodes.pyc" />
        <File name="optimizer" src="libs/jinja2/optimizer.pyc" />
        <File name="parser" src="libs/jinja2/parser.pyc" />
        <File name="runtime" src="libs/jinja2/runtime.pyc" />
        <File name="sandbox" src="libs/jinja2/sandbox.pyc" />
        <File name="tests" src="libs/jinja2/tests.pyc" />
        <File name="utils" src="libs/jinja2/utils.pyc" />
        <File name="visitor" src="libs/jinja2/visitor.pyc" />
        <File name="METADATA" src="libs/Flask-1.1.2.dist-info/METADATA" />
        <File name="RECORD" src="libs/Flask-1.1.2.dist-info/RECORD" />
        <File name="top_level" src="libs/Flask-1.1.2.dist-info/top_level.txt" />
        <File name="_compat" src="libs/click/_compat.py" />
        <File name="INSTALLER" src="libs/Flask-1.1.2.dist-info/INSTALLER" />
        <File name="LICENSE" src="libs/Flask-1.1.2.dist-info/LICENSE.rst" />
        <File name="WHEEL" src="libs/Flask-1.1.2.dist-info/WHEEL" />
        <File name="entry_points" src="libs/Flask-1.1.2.dist-info/entry_points.txt" />
        <File name="core" src="libs/click/core.py" />
        <File name="core" src="libs/click/core.pyc" />
        <File name="__init__" src="libs/flask/__init__.py" />
        <File name="__main__" src="libs/flask/__main__.py" />
        <File name="_compat" src="libs/flask/_compat.py" />
        <File name="app" src="libs/flask/app.py" />
        <File name="blueprints" src="libs/flask/blueprints.py" />
        <File name="cli" src="libs/flask/cli.py" />
        <File name="config" src="libs/flask/config.py" />
        <File name="ctx" src="libs/flask/ctx.py" />
        <File name="debughelpers" src="libs/flask/debughelpers.py" />
        <File name="globals" src="libs/flask/globals.py" />
        <File name="helpers" src="libs/flask/helpers.py" />
        <File name="__init__" src="libs/flask/json/__init__.py" />
        <File name="tag" src="libs/flask/json/tag.py" />
        <File name="logging" src="libs/flask/logging.py" />
        <File name="sessions" src="libs/flask/sessions.py" />
        <File name="signals" src="libs/flask/signals.py" />
        <File name="templating" src="libs/flask/templating.py" />
        <File name="testing" src="libs/flask/testing.py" />
        <File name="views" src="libs/flask/views.py" />
        <File name="wrappers" src="libs/flask/wrappers.py" />
        <File name="__init__" src="libs/werkzeug/debug/__init__.py" />
        <File name="__init__" src="libs/werkzeug/debug/__init__.pyc" />
        <File name="console" src="libs/werkzeug/debug/console.py" />
        <File name="console" src="libs/werkzeug/debug/console.pyc" />
        <File name="repr" src="libs/werkzeug/debug/repr.py" />
        <File name="repr" src="libs/werkzeug/debug/repr.pyc" />
        <File name="FONT_LICENSE" src="libs/werkzeug/debug/shared/FONT_LICENSE" />
        <File name="console" src="libs/werkzeug/debug/shared/console.png" />
        <File name="debugger" src="libs/werkzeug/debug/shared/debugger.js" />
        <File name="jquery" src="libs/werkzeug/debug/shared/jquery.js" />
        <File name="less" src="libs/werkzeug/debug/shared/less.png" />
        <File name="more" src="libs/werkzeug/debug/shared/more.png" />
        <File name="source" src="libs/werkzeug/debug/shared/source.png" />
        <File name="style" src="libs/werkzeug/debug/shared/style.css" />
        <File name="ubuntu" src="libs/werkzeug/debug/shared/ubuntu.ttf" />
        <File name="tbtools" src="libs/werkzeug/debug/tbtools.pyc" />
        <File name="__init__" src="libs/werkzeug/middleware/__init__.py" />
        <File name="__init__" src="libs/werkzeug/middleware/__init__.pyc" />
        <File name="dispatcher" src="libs/werkzeug/middleware/dispatcher.py" />
        <File name="dispatcher" src="libs/werkzeug/middleware/dispatcher.pyc" />
        <File name="http_proxy" src="libs/werkzeug/middleware/http_proxy.py" />
        <File name="http_proxy" src="libs/werkzeug/middleware/http_proxy.pyc" />
        <File name="lint" src="libs/werkzeug/middleware/lint.py" />
        <File name="lint" src="libs/werkzeug/middleware/lint.pyc" />
        <File name="profiler" src="libs/werkzeug/middleware/profiler.py" />
        <File name="profiler" src="libs/werkzeug/middleware/profiler.pyc" />
        <File name="proxy_fix" src="libs/werkzeug/middleware/proxy_fix.py" />
        <File name="proxy_fix" src="libs/werkzeug/middleware/proxy_fix.pyc" />
        <File name="shared_data" src="libs/werkzeug/middleware/shared_data.py" />
        <File name="shared_data" src="libs/werkzeug/middleware/shared_data.pyc" />
        <File name="__init__" src="libs/itsdangerous/__init__.py" />
        <File name="__init__" src="libs/itsdangerous/__init__.pyc" />
        <File name="_compat" src="libs/itsdangerous/_compat.py" />
        <File name="_compat" src="libs/itsdangerous/_compat.pyc" />
        <File name="_json" src="libs/itsdangerous/_json.py" />
        <File name="_json" src="libs/itsdangerous/_json.pyc" />
        <File name="encoding" src="libs/itsdangerous/encoding.py" />
        <File name="encoding" src="libs/itsdangerous/encoding.pyc" />
        <File name="exc" src="libs/itsdangerous/exc.py" />
        <File name="exc" src="libs/itsdangerous/exc.pyc" />
        <File name="jws" src="libs/itsdangerous/jws.py" />
        <File name="jws" src="libs/itsdangerous/jws.pyc" />
        <File name="serializer" src="libs/itsdangerous/serializer.py" />
        <File name="serializer" src="libs/itsdangerous/serializer.pyc" />
        <File name="signer" src="libs/itsdangerous/signer.py" />
        <File name="signer" src="libs/itsdangerous/signer.pyc" />
        <File name="timed" src="libs/itsdangerous/timed.py" />
        <File name="timed" src="libs/itsdangerous/timed.pyc" />
        <File name="url_safe" src="libs/itsdangerous/url_safe.py" />
        <File name="url_safe" src="libs/itsdangerous/url_safe.pyc" />
        <File name="__init__" src="libs/markupsafe/__init__.py" />
        <File name="__init__" src="libs/markupsafe/__init__.pyc" />
        <File name="_compat" src="libs/markupsafe/_compat.py" />
        <File name="_compat" src="libs/markupsafe/_compat.pyc" />
        <File name="_constants" src="libs/markupsafe/_constants.py" />
        <File name="_constants" src="libs/markupsafe/_constants.pyc" />
        <File name="_native" src="libs/markupsafe/_native.py" />
        <File name="_native" src="libs/markupsafe/_native.pyc" />
        <File name="_speedups" src="libs/markupsafe/_speedups.c" />
        <File name="_speedups" src="libs/markupsafe/_speedups.so" />
        <File name="__init__" src="libs/werkzeug/__init__.py" />
        <File name="__init__" src="libs/werkzeug/__init__.pyc" />
        <File name="_compat" src="libs/werkzeug/_compat.py" />
        <File name="_compat" src="libs/werkzeug/_compat.pyc" />
        <File name="_internal" src="libs/werkzeug/_internal.py" />
        <File name="_internal" src="libs/werkzeug/_internal.pyc" />
        <File name="_reloader" src="libs/werkzeug/_reloader.py" />
        <File name="_reloader" src="libs/werkzeug/_reloader.pyc" />
        <File name="datastructures" src="libs/werkzeug/datastructures.py" />
        <File name="datastructures" src="libs/werkzeug/datastructures.pyc" />
        <File name="tbtools" src="libs/werkzeug/debug/tbtools.py" />
        <File name="exceptions" src="libs/werkzeug/exceptions.py" />
        <File name="exceptions" src="libs/werkzeug/exceptions.pyc" />
        <File name="filesystem" src="libs/werkzeug/filesystem.py" />
        <File name="filesystem" src="libs/werkzeug/filesystem.pyc" />
        <File name="formparser" src="libs/werkzeug/formparser.py" />
        <File name="formparser" src="libs/werkzeug/formparser.pyc" />
        <File name="http" src="libs/werkzeug/http.py" />
        <File name="http" src="libs/werkzeug/http.pyc" />
        <File name="local" src="libs/werkzeug/local.py" />
        <File name="local" src="libs/werkzeug/local.pyc" />
        <File name="posixemulation" src="libs/werkzeug/posixemulation.py" />
        <File name="posixemulation" src="libs/werkzeug/posixemulation.pyc" />
        <File name="routing" src="libs/werkzeug/routing.py" />
        <File name="routing" src="libs/werkzeug/routing.pyc" />
        <File name="security" src="libs/werkzeug/security.py" />
        <File name="security" src="libs/werkzeug/security.pyc" />
        <File name="serving" src="libs/werkzeug/serving.py" />
        <File name="serving" src="libs/werkzeug/serving.pyc" />
        <File name="test" src="libs/werkzeug/test.py" />
        <File name="test" src="libs/werkzeug/test.pyc" />
        <File name="testapp" src="libs/werkzeug/testapp.py" />
        <File name="testapp" src="libs/werkzeug/testapp.pyc" />
        <File name="urls" src="libs/werkzeug/urls.py" />
        <File name="urls" src="libs/werkzeug/urls.pyc" />
        <File name="useragents" src="libs/werkzeug/useragents.py" />
        <File name="useragents" src="libs/werkzeug/useragents.pyc" />
        <File name="utils" src="libs/werkzeug/utils.py" />
        <File name="utils" src="libs/werkzeug/utils.pyc" />
        <File name="__init__" src="libs/werkzeug/wrappers/__init__.py" />
        <File name="__init__" src="libs/werkzeug/wrappers/__init__.pyc" />
        <File name="accept" src="libs/werkzeug/wrappers/accept.py" />
        <File name="accept" src="libs/werkzeug/wrappers/accept.pyc" />
        <File name="auth" src="libs/werkzeug/wrappers/auth.py" />
        <File name="auth" src="libs/werkzeug/wrappers/auth.pyc" />
        <File name="base_request" src="libs/werkzeug/wrappers/base_request.py" />
        <File name="base_request" src="libs/werkzeug/wrappers/base_request.pyc" />
        <File name="base_response" src="libs/werkzeug/wrappers/base_response.py" />
        <File name="base_response" src="libs/werkzeug/wrappers/base_response.pyc" />
        <File name="common_descriptors" src="libs/werkzeug/wrappers/common_descriptors.py" />
        <File name="common_descriptors" src="libs/werkzeug/wrappers/common_descriptors.pyc" />
        <File name="cors" src="libs/werkzeug/wrappers/cors.py" />
        <File name="cors" src="libs/werkzeug/wrappers/cors.pyc" />
        <File name="etag" src="libs/werkzeug/wrappers/etag.py" />
        <File name="etag" src="libs/werkzeug/wrappers/etag.pyc" />
        <File name="json" src="libs/werkzeug/wrappers/json.py" />
        <File name="json" src="libs/werkzeug/wrappers/json.pyc" />
        <File name="request" src="libs/werkzeug/wrappers/request.py" />
        <File name="request" src="libs/werkzeug/wrappers/request.pyc" />
        <File name="response" src="libs/werkzeug/wrappers/response.py" />
        <File name="response" src="libs/werkzeug/wrappers/response.pyc" />
        <File name="user_agent" src="libs/werkzeug/wrappers/user_agent.py" />
        <File name="user_agent" src="libs/werkzeug/wrappers/user_agent.pyc" />
        <File name="wsgi" src="libs/werkzeug/wsgi.py" />
        <File name="wsgi" src="libs/werkzeug/wsgi.pyc" />
        <File name="" src=".gitignore" />
        <File name="server" src="certs/server.crt" />
        <File name="__init__" src="libs/dotenv/__init__.py" />
        <File name="__init__" src="libs/dotenv/__init__.pyc" />
        <File name="cli" src="libs/dotenv/cli.py" />
        <File name="cli" src="libs/dotenv/cli.pyc" />
        <File name="compat" src="libs/dotenv/compat.py" />
        <File name="compat" src="libs/dotenv/compat.pyc" />
        <File name="ipython" src="libs/dotenv/ipython.py" />
        <File name="ipython" src="libs/dotenv/ipython.pyc" />
        <File name="main" src="libs/dotenv/main.py" />
        <File name="main" src="libs/dotenv/main.pyc" />
        <File name="parser" src="libs/dotenv/parser.py" />
        <File name="parser" src="libs/dotenv/parser.pyc" />
        <File name="py" src="libs/dotenv/py.typed" />
        <File name="variables" src="libs/dotenv/variables.py" />
        <File name="variables" src="libs/dotenv/variables.pyc" />
        <File name="version" src="libs/dotenv/version.py" />
        <File name="version" src="libs/dotenv/version.pyc" />
        <File name="" src=".env" />
        <File name="RICE_arborio" src="html/img/RICE_arborio.png" />
        <File name="RICE_baldo" src="html/img/RICE_baldo.png" />
        <File name="RICE_basmati" src="html/img/RICE_basmati.png" />
        <File name="RICE_carnaroli" src="html/img/RICE_carnaroli.png" />
        <File name="RICE_jasmine" src="html/img/RICE_jasmine.png" />
        <File name="RICE_ofada" src="html/img/RICE_ofada.png" />
        <File name="RICE_venere" src="html/img/RICE_venere.png" />
        <File name="master" src="libs/cairlib/.git/logs/refs/heads/master" />
        <File name="v4" src="libs/cairlib/.git/logs/refs/heads/v4.0" />
        <File name="HEAD" src="libs/cairlib/.git/logs/refs/remotes/origin/HEAD" />
        <File name="master" src="libs/cairlib/.git/logs/refs/remotes/origin/master" />
        <File name="v3" src="libs/cairlib/.git/logs/refs/remotes/origin/v3.0" />
        <File name="v4" src="libs/cairlib/.git/logs/refs/remotes/origin/v4.0" />
        <File name="6de686384a5e3abe44096098276d393877a2c2" src="libs/cairlib/.git/objects/42/6de686384a5e3abe44096098276d393877a2c2" />
        <File name="1b89aeeda0de1c87f3cb28ddb64039dc9b6883" src="libs/cairlib/.git/objects/95/1b89aeeda0de1c87f3cb28ddb64039dc9b6883" />
        <File name="378ad99d4d1453cb89d27e9ff6883ce378ff79" src="libs/cairlib/.git/objects/95/378ad99d4d1453cb89d27e9ff6883ce378ff79" />
        <File name="3c5612c21c82e839ba40d16c6b26771c1046b6" src="libs/cairlib/.git/objects/95/3c5612c21c82e839ba40d16c6b26771c1046b6" />
        <File name="8d86984ba4f6e92b7675e3ce9771838f05e748" src="libs/cairlib/.git/objects/95/8d86984ba4f6e92b7675e3ce9771838f05e748" />
        <File name="d8011740a98e23a86f49d80a2357eb652c7562" src="libs/cairlib/.git/objects/95/d8011740a98e23a86f49d80a2357eb652c7562" />
        <File name="3a203cab4dc1a1eeb215578766610dbee30dde" src="libs/cairlib/.git/objects/ab/3a203cab4dc1a1eeb215578766610dbee30dde" />
        <File name="cea446d4ba4a7d6b0bfc0b8d1b59be88949816" src="libs/cairlib/.git/objects/ab/cea446d4ba4a7d6b0bfc0b8d1b59be88949816" />
        <File name="cff5d6df401b36d055ff63bbd67690d1ef7290" src="libs/cairlib/.git/objects/ab/cff5d6df401b36d055ff63bbd67690d1ef7290" />
        <File name="498de28b6083a405a38698453d8df4a8c421cc" src="libs/cairlib/.git/objects/b8/498de28b6083a405a38698453d8df4a8c421cc" />
        <File name="b74fcf8163944f854a44ff683c29cfedab1056" src="libs/cairlib/.git/objects/b8/b74fcf8163944f854a44ff683c29cfedab1056" />
        <File name="c51ac655f357e3d75f8c324f93b0c2a2b5f320" src="libs/cairlib/.git/objects/b8/c51ac655f357e3d75f8c324f93b0c2a2b5f320" />
        <File name="98056571693c92ff9e80b10e9d735f8becec50" src="libs/cairlib/.git/objects/ba/98056571693c92ff9e80b10e9d735f8becec50" />
        <File name="689e3bf1f601351a54619ffa886ecee7fccf63" src="libs/cairlib/.git/objects/c5/689e3bf1f601351a54619ffa886ecee7fccf63" />
        <File name="c16c66f9555e7f445466f239c165a81c22c2b7" src="libs/cairlib/.git/objects/c5/c16c66f9555e7f445466f239c165a81c22c2b7" />
        <File name="3646f7ace8dc5f3adc0c6e8c758dbb9fb1713a" src="libs/cairlib/.git/objects/c6/3646f7ace8dc5f3adc0c6e8c758dbb9fb1713a" />
        <File name="f2d780c420e7f995ebb446b97ccaa01450e8fe" src="libs/cairlib/.git/objects/c6/f2d780c420e7f995ebb446b97ccaa01450e8fe" />
        <File name="9ea7b2fdacd0d684cf47566a3b6925ffa97926" src="libs/cairlib/.git/objects/c8/9ea7b2fdacd0d684cf47566a3b6925ffa97926" />
        <File name="23a5049970ac60343185ba50665f4eb37dc0bd" src="libs/cairlib/.git/objects/cb/23a5049970ac60343185ba50665f4eb37dc0bd" />
        <File name="75512e35d14990ba1a396ba5d6265333e8e1b3" src="libs/cairlib/.git/objects/cb/75512e35d14990ba1a396ba5d6265333e8e1b3" />
        <File name="82edfd34e35d0e5892d219b184d0a565f59451" src="libs/cairlib/.git/objects/cb/82edfd34e35d0e5892d219b184d0a565f59451" />
        <File name="973ff20dcf11f30d14e5f1bfba294ba8609b0a" src="libs/cairlib/.git/objects/d0/973ff20dcf11f30d14e5f1bfba294ba8609b0a" />
        <File name="3886a58dec1e8e28744ed17cd3987604b9085d" src="libs/cairlib/.git/objects/d3/3886a58dec1e8e28744ed17cd3987604b9085d" />
        <File name="55bbd002aa35156b6f65fcd6b7ad186a87f69c" src="libs/cairlib/.git/objects/d3/55bbd002aa35156b6f65fcd6b7ad186a87f69c" />
        <File name="160e130bf07116d373409683b3243e4c56d21c" src="libs/cairlib/.git/objects/d9/160e130bf07116d373409683b3243e4c56d21c" />
        <File name="7a35df37d2d65de9de4c344256469f501ea883" src="libs/cairlib/.git/objects/d9/7a35df37d2d65de9de4c344256469f501ea883" />
        <File name="23fed4c374322d55e3feadfa160888172938f0" src="libs/cairlib/.git/objects/dc/23fed4c374322d55e3feadfa160888172938f0" />
        <File name="ecc910054e99f552ae04110fc10165cec66e56" src="libs/cairlib/.git/objects/dc/ecc910054e99f552ae04110fc10165cec66e56" />
        <File name="0a4c6fd049dcaad9a65a94e2f46501ec6b811d" src="libs/cairlib/.git/objects/e0/0a4c6fd049dcaad9a65a94e2f46501ec6b811d" />
        <File name="d482da90ad6da899a4be14a8e8af595fde099e" src="libs/cairlib/.git/objects/e0/d482da90ad6da899a4be14a8e8af595fde099e" />
        <File name="8c3bdb26a68fdf007c9704c290a6d81cafc2fc" src="libs/cairlib/.git/objects/e5/8c3bdb26a68fdf007c9704c290a6d81cafc2fc" />
        <File name="a958c0f665049a81cda17d491ae30ca88cf30b" src="libs/cairlib/.git/objects/e5/a958c0f665049a81cda17d491ae30ca88cf30b" />
        <File name="7995e5b32d9fbbd5e8eb6475ff3d999bee27f3" src="libs/cairlib/.git/objects/e6/7995e5b32d9fbbd5e8eb6475ff3d999bee27f3" />
        <File name="8fb37981d9ba9bb6b2e0fc3add14dba9afdae9" src="libs/cairlib/.git/objects/e6/8fb37981d9ba9bb6b2e0fc3add14dba9afdae9" />
        <File name="412a2381e96e03359014b97c14ce328dc62778" src="libs/cairlib/.git/objects/e9/412a2381e96e03359014b97c14ce328dc62778" />
        <File name="b6132de83c57a29436b303868f316b0ecb1187" src="libs/cairlib/.git/objects/e9/b6132de83c57a29436b303868f316b0ecb1187" />
        <File name="3b2a0567c6e603806a5b0d98c6ac6a710e2d9f" src="libs/cairlib/.git/objects/ec/3b2a0567c6e603806a5b0d98c6ac6a710e2d9f" />
        <File name="7855ae1694ec75e43c090d92921c20cd145276" src="libs/cairlib/.git/objects/ec/7855ae1694ec75e43c090d92921c20cd145276" />
        <File name="914fcd14777b1cbab0cbde5dca8b5a8cffcc42" src="libs/cairlib/.git/objects/f7/914fcd14777b1cbab0cbde5dca8b5a8cffcc42" />
        <File name="a81bfec996160c86378eb1066da6ab2d1dd261" src="libs/cairlib/.git/objects/f7/a81bfec996160c86378eb1066da6ab2d1dd261" />
        <File name="180c1e682aad1726bc9ff463d6eb0d82edec11" src="libs/cairlib/.git/objects/fa/180c1e682aad1726bc9ff463d6eb0d82edec11" />
        <File name="7bcaf90467caac50c5af4f9542a83cdfff74d8" src="libs/cairlib/.git/objects/fa/7bcaf90467caac50c5af4f9542a83cdfff74d8" />
        <File name="cc2305bd4eb34b59df71d78588651943a41dc0" src="libs/cairlib/.git/objects/fa/cc2305bd4eb34b59df71d78588651943a41dc0" />
        <File name="589eac869174f3bf14be62b7155413ec6fbba4" src="libs/cairlib/.git/objects/ff/589eac869174f3bf14be62b7155413ec6fbba4" />
        <File name="b071f5ff13c41d15678c5e8517dd811a3b2ff1" src="libs/cairlib/.git/objects/ff/b071f5ff13c41d15678c5e8517dd811a3b2ff1" />
        <File name="pack-4c787ee7705a6a6d7ee49b47d4bcb22c27d05092" src="libs/cairlib/.git/objects/pack/pack-4c787ee7705a6a6d7ee49b47d4bcb22c27d05092.idx" />
        <File name="pack-4c787ee7705a6a6d7ee49b47d4bcb22c27d05092" src="libs/cairlib/.git/objects/pack/pack-4c787ee7705a6a6d7ee49b47d4bcb22c27d05092.pack" />
        <File name="master" src="libs/cairlib/.git/refs/heads/master" />
        <File name="v4" src="libs/cairlib/.git/refs/heads/v4.0" />
        <File name="HEAD" src="libs/cairlib/.git/refs/remotes/origin/HEAD" />
        <File name="master" src="libs/cairlib/.git/refs/remotes/origin/master" />
        <File name="v3" src="libs/cairlib/.git/refs/remotes/origin/v3.0" />
        <File name="v4" src="libs/cairlib/.git/refs/remotes/origin/v4.0" />
        <File name="server_130_251_13_192" src="certs/server_130_251_13_192.crt" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
        <Translation name="translation_it_IT" src="translations/translation_it_IT.ts" language="it_IT" />
    </Translations>
</Package>
